// Generated by Skyramp v1.3.13 on 2026-03-18 01:08:00.571602815 +0000 UTC m=+87.740521221
// Command: skyramp generate integration rest \
// 		--auth-header X-Parse-Application-Id \
// 		--framework playwright \
// 		--language typescript \
// 		--output batch_create_integration_test.ts \
// 		--output-dir /home/runner/work/parse-server-example/parse-server-example/spec \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/parse-server-example/parse-server-example/spec/scenario_batch_create_and_verify_1742286000.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:1337");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Declaration of variables
    let classes = "TestItem";
    let classes_1 = getValue(batchCreatePostResponse, "result.ids.0");

    // Request Body
    const batchCreatePostRequestBody = `{
            "className": "TestItem",
            "objects": [
                {
                    "name": "Widget A",
                    "price": 9.99
                },
                {
                    "name": "Widget B",
                    "price": 14.99
                }
            ]
        }`
    
    // Execute Request
    let batchCreatePostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/parse/functions/batchCreate",
        method:"POST",
        body:batchCreatePostRequestBody,
        headers:{"X-Parse-Application-Id": "TestBotAppId"}
    });

    // Generated Assertions
    expect(batchCreatePostResponse.statusCode, 'status code').toBe(200);

    // Execute Request
    let classes1GetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/parse/classes/{classes}/{classes_1}",
        method:"GET",
        headers:{"X-Parse-Application-Id": "TestBotAppId"},
        pathParams:{
            "classes": classes,
            "classes_1": classes_1
        }
    });

    // Generated Assertions
    expect(classes1GetResponse.statusCode, 'status code').toBe(200);
});

