// Generated by Skyramp v1.3.13 on 2026-03-18 01:08:06.616819818 +0000 UTC m=+93.785738264
// Command: skyramp generate fuzz rest http://localhost:1337/parse/functions/batchCreate \
// 		--auth-header X-Parse-Application-Id \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output batch_create_fuzz_test.ts \
// 		--output-dir /home/runner/work/parse-server-example/parse-server-example/spec \
// 		--overwrite \
// 		--provider \
// 		--request-data {"className":"TestItem","objects":[{"name":"Widget A","price":9.99}]} \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:1337");

// fuzz test for /parse/functions/batchCreate POST
test('testBatchCreatePost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["X-Parse-Application-Id"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const batchCreatePostRequestBody = `{
            "className": "TestItem",
            "objects": [
                {
                    "name": "Widget A",
                    "price": 9.99
                }
            ]
        }`
    
    // Fuzz strategies
    const batchCreatePostFuzzedBody = {
        "className": "0123456789",
        "objects": [{
            "name": "0123456789",
            "price": -10
        }]
    };
    // Fuzz status codes
    const expectedBatchCreatePostStatusCode: Record<string, string> = {
        "className": "40x",
        "objects": [{
            "name": "40x",
            "price": "40x"
        }]
    };
    // Fuzz status codes for Null values
    const expectedBatchCreatePostNullStatusCode: Record<string, string> = {
        "className": "40x",
        "objects": [{
            "name": "40x",
            "price": "40x"
        }]
    };

    // Execute Request
    let batchCreatePostResponse = await client.sendRequest({
        url:URL,
        path:"/parse/functions/batchCreate",
        method:"POST",
        body:batchCreatePostRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(batchCreatePostFuzzedBody)) {
        // Execute Request
        batchCreatePostResponse = await client.sendRequest({
            url:URL,
            path:"/parse/functions/batchCreate",
            method:"POST",
            body:batchCreatePostRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(batchCreatePostFuzzedBody, key)},
            expectedCode:getValue(expectedBatchCreatePostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(batchCreatePostFuzzedBody, key)}`
        });


        // Execute Request
        batchCreatePostResponse = await client.sendRequest({
            url:URL,
            path:"/parse/functions/batchCreate",
            method:"POST",
            body:batchCreatePostRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedBatchCreatePostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

