// Generated by Skyramp v1.3.13 on 2026-03-18 04:24:08.28676053 +0000 UTC m=+107.214060471
// Command: skyramp generate integration rest \
// 		--auth-header X-Parse-Application-Id \
// 		--framework playwright \
// 		--language typescript \
// 		--output batchCreate_integration_test.spec.ts \
// 		--output-dir /home/runner/work/parse-server-example/parse-server-example/spec \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/parse-server-example/parse-server-example/spec/scenario_batchcreate_integration_1748.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:1337");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Declaration of variables
    let classes = "TestItem";

    // Request Body
    const batchCreatePostRequestBody = `{
            "className": "TestItem",
            "objects": [
                {
                    "name": "Item One",
                    "value": 42
                },
                {
                    "name": "Item Two",
                    "value": 99
                }
            ]
        }`

    // Execute Request
    let batchCreatePostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/parse/functions/batchCreate",
        method:"POST",
        body:batchCreatePostRequestBody,
        headers:{"X-Parse-Application-Id": "SKYRAMP_PLACEHOLDER_TOKEN"}
    });

    // Generated Assertions
    expect(batchCreatePostResponse.statusCode, 'status code').toBe(200);

    // Chain ID from batchCreate response
    let classes_1 = getValue(batchCreatePostResponse, "result.ids[0]");

    // Execute Request
    let classes1GetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/parse/classes/{classes}/{classes_1}",
        method:"GET",
        headers:{"X-Parse-Application-Id": "SKYRAMP_PLACEHOLDER_TOKEN"},
        pathParams:{
            "classes": classes,
            "classes_1": classes_1
        }
    });

    // Generated Assertions
    expect(classes1GetResponse.statusCode, 'status code').toBe(200);
});

