// Generated by Skyramp v1.3.13 on 2026-03-18 01:08:04.342228348 +0000 UTC m=+91.511146754
// Command: skyramp generate contract rest http://localhost:1337/parse/functions/batchCreate \
// 		--auth-header X-Parse-Application-Id \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output batch_create_contract_test.ts \
// 		--output-dir /home/runner/work/parse-server-example/parse-server-example/spec \
// 		--overwrite \
// 		--provider \
// 		--request-data {"className":"TestItem","objects":[{"name":"Widget A","price":9.99}]} \
// 		--response-status-code 200 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:1337");

// contract test for /parse/functions/batchCreate POST
test('testBatchCreatePost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["X-Parse-Application-Id"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const batchCreatePostRequestBody: string = `{
        "className": "TestItem",
        "objects": [
            {
                "name": "Widget A",
                "price": 9.99
            }
        ]
    }`;

    // Execute Request
    const batchCreatePostResponse = await client.sendRequest({
        url: URL,
        path: "/parse/functions/batchCreate",
        method: "POST",
        body: batchCreatePostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(batchCreatePostResponse.statusCode, 'status code').toBe(200);
});
