// Generated by Skyramp v1.3.14 on 2026-03-24 22:31:52.687362584 +0000 UTC m=+116.519121184
// Command: skyramp generate contract rest http://localhost:1337/parse/functions/getRecentObjects \
// 		--auth-header X-Parse-Master-Key \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output contract_get_recent_objects_missing_classname.spec.ts \
// 		--output-dir /home/runner/work/parse-server-example/parse-server-example/spec \
// 		--overwrite \
// 		--provider \
// 		--runtime local

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:1337");

// contract test for /parse/functions/getRecentObjects POST
test('testGetRecentObjectsPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["X-Parse-Master-Key"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const getRecentObjectsPostRequestBody: string = `{}`;

    // Execute Request
    const getRecentObjectsPostResponse = await client.sendRequest({
        url: URL,
        path: "/parse/functions/getRecentObjects",
        method: "POST",
        body: getRecentObjectsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(getRecentObjectsPostResponse, "20x"), 'status code').toBeTruthy();
});
