// Generated by Skyramp v1.3.13 on 2026-03-18 00:58:25.338065075 +0000 UTC m=+91.170502674
// Command: skyramp generate contract rest http://localhost:1337/parse/functions/health \
// 		--auth-header X-Parse-Application-Id \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output contract_health.spec.ts \
// 		--output-dir /home/runner/work/parse-server-example/parse-server-example/spec \
// 		--overwrite \
// 		--provider \
// 		--response-status-code 200 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:1337");

// contract test for /parse/functions/health POST
test('testHealthPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["X-Parse-Application-Id"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const healthPostRequestBody: string = `{}`;

    // Execute Request
    const healthPostResponse = await client.sendRequest({
        url: URL,
        path: "/parse/functions/health",
        method: "POST",
        body: healthPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(healthPostResponse.statusCode, 'status code').toBe(200);
});
