// Generated by Skyramp v1.3.13 on 2026-03-18 14:16:38.316040956 +0000 UTC m=+82.651846459
// Command: skyramp generate contract rest http://localhost:1337/1/functions/health \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output-dir /home/runner/work/parse-server-example/parse-server-example/spec \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, checkStatusCode, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:1337");

// contract test for /1/functions/health POST
test('testHealthPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const healthPostRequestBody: string = `{}`;

    // Execute Request
    const healthPostResponse = await client.sendRequest({
        url: URL,
        path: "/1/functions/health",
        method: "POST",
        body: healthPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(checkStatusCode(healthPostResponse, "20x"), 'status code').toBeTruthy();
});
