// Generated by Skyramp v1.3.13 on 2026-03-18 04:14:36.506571848 +0000 UTC m=+89.208354730
// Command: skyramp generate fuzz rest http://localhost:1337/parse/functions/health \
// 		--auth-header X-Parse-Application-Id \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output health_fuzz.spec.ts \
// 		--output-dir /home/runner/work/parse-server-example/parse-server-example/spec \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, iterate } from '@skyramp/skyramp';

// URL for test requests
let URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:1337");

// fuzz test for /parse/functions/health POST
test('testHealthPost', async () => {
    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["X-Parse-Application-Id"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const healthPostRequestBody = `{}`
    
    // Fuzz strategies
    const healthPostFuzzedBody = {};
    // Fuzz status codes
    const expectedHealthPostStatusCode: Record<string, string> = "40x";
    // Fuzz status codes for Null values
    const expectedHealthPostNullStatusCode: Record<string, string> = "40x";

    // Execute Request
    let healthPostResponse = await client.sendRequest({
        url:URL,
        path:"/parse/functions/health",
        method:"POST",
        body:healthPostRequestBody,
        headers:headers,
        expectedCode:"20x"
    });


    for (const key of iterate(healthPostFuzzedBody)) {
        // Execute Request
        healthPostResponse = await client.sendRequest({
            url:URL,
            path:"/parse/functions/health",
            method:"POST",
            body:healthPostRequestBody,
            headers:headers,
            dataOverride:{[key]: getValue(healthPostFuzzedBody, key)},
            expectedCode:getValue(expectedHealthPostStatusCode, key),
            description:`Fuzzing request body ${key} to ${getValue(healthPostFuzzedBody, key)}`
        });


        // Execute Request
        healthPostResponse = await client.sendRequest({
            url:URL,
            path:"/parse/functions/health",
            method:"POST",
            body:healthPostRequestBody,
            headers:headers,
            dataOverride:{[key]: null},
            expectedCode:getValue(expectedHealthPostNullStatusCode, key),
            description:`Fuzzing request body ${key} to null`
        });
    }


    expect(client.isSuccess(), 'fuzz test').toBeTruthy();
});

