// Generated by Skyramp v1.3.13 on 2026-03-18 01:35:12.162164256 +0000 UTC m=+108.059777740
// Command: skyramp generate integration rest \
// 		--auth-header X-Parse-Application-Id \
// 		--framework playwright \
// 		--language typescript \
// 		--output health_integration_test.ts \
// 		--output-dir /home/runner/work/parse-server-example/parse-server-example/spec \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/parse-server-example/parse-server-example/spec/scenario_health_check_db_connectivity.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:1337");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Request Body
    const healthPostRequestBody = `{}`
    
    // Execute Request
    let healthPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/parse/functions/health",
        method:"POST",
        body:healthPostRequestBody,
        headers:{"X-Parse-Application-Id": "myAppId"}
    });

    // Generated Assertions
    expect(healthPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const healthProbePostRequestBody = `{
            "probe": "connectivity-check",
            "ts": "2026-03-18T00:00:00.000Z"
        }`
    
    // Execute Request
    let healthProbePostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/parse/classes/HealthProbe",
        method:"POST",
        body:healthProbePostRequestBody,
        headers:{"X-Parse-Application-Id": "myAppId"},
        dataOverride:{"ts": getResponseValue(healthPostResponse, "result.timestamp")}
    });

    // Generated Assertions
    expect(healthProbePostResponse.statusCode, 'status code').toBe(201);
});

