// Generated by Skyramp v1.3.13 on 2026-03-18 01:00:56.129637754 +0000 UTC m=+241.962075353
// Command: skyramp generate integration rest \
// 		--auth-header X-Parse-Application-Id \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /home/runner/work/parse-server-example/parse-server-example/spec \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/parse-server-example/parse-server-example/spec/scenario_health_check_cloud_function.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:1337");

test('testIntegration', async () => {
    test.setTimeout(170000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Request Body
    const healthPostRequestBody = `{}`
    
    // Execute Request
    let healthPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/parse/functions/health",
        method:"POST",
        body:healthPostRequestBody,
        headers:{"X-Parse-Application-Id": "myAppId"}
    });

    // Generated Assertions
    expect(healthPostResponse.statusCode, 'status code').toBe(200);

    // Request Body
    const healthPost1RequestBody = `{}`
    
    // Execute Request
    let healthPost1Response = await client.sendRequest({
        url:URL_localhost,
        path:"/parse/functions/health",
        method:"POST",
        body:healthPost1RequestBody,
        headers:{"X-Parse-Application-Id": "TestBotAppId"}
    });

    // Generated Assertions
    expect(healthPost1Response.statusCode, 'status code').toBe(200);
});

