// Generated by Skyramp v1.3.13 on 2026-03-18 01:42:46.354700778 +0000 UTC m=+138.653197602
// Command: skyramp generate integration rest \
// 		--auth-header X-Parse-Session-Token \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /home/runner/work/parse-server-example/parse-server-example/spec \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/parse-server-example/parse-server-example/spec/scenario_batchcreate_integration.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:1337");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Declaration of variables
    let classes = "GameScore";

    // Request Body
    const batchCreatePostRequestBody = `{
            "className": "GameScore",
            "objects": [
                {
                    "playerName": "Alice",
                    "score": 42
                },
                {
                    "playerName": "Bob",
                    "score": 99
                }
            ]
        }`
    
    // Execute Request
    let batchCreatePostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/parse/functions/batchCreate",
        method:"POST",
        body:batchCreatePostRequestBody,
        headers:{"X-Parse-Session-Token": "r:5d4b827449d2f40499886ace35b9a1b2"}
    });

    // Generated Assertions
    expect(batchCreatePostResponse.statusCode, 'status code').toBe(200);

    let classes_1 = getValue(batchCreatePostResponse.body, "result.ids.0");

    // Execute Request
    let classes1GetResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/parse/classes/{classes}/{classes_1}",
        method:"GET",
        headers:{"X-Parse-Session-Token": "r:5d4b827449d2f40499886ace35b9a1b2"},
        pathParams:{
            "classes": classes,
            "classes_1": classes_1
        }
    });

    // Generated Assertions
    expect(classes1GetResponse.statusCode, 'status code').toBe(200);
});

