// Generated by Skyramp v1.3.13 on 2026-03-18 14:16:46.265126414 +0000 UTC m=+90.600931927
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output-dir /home/runner/work/parse-server-example/parse-server-example/spec \
// 		--overwrite \
// 		--provider \
// 		--runtime local \
// 		--skipProvisionParents \
// 		--trace /home/runner/work/parse-server-example/parse-server-example/spec/scenario_health_check_workflow.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:1337");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const healthPostRequestBody = `{}`
    
    // Execute Request
    let healthPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/1/functions/health",
        method:"POST",
        body:healthPostRequestBody,
        headers:headers
    });

    // Generated Assertions
    expect(healthPostResponse.statusCode, 'status code').toBe(200);
});

