// Generated by Skyramp v1.3.14 on 2026-03-24 22:32:23.446887699 +0000 UTC m=+147.278646281
// Command: skyramp generate integration rest \
// 		--auth-header X-Parse-Master-Key \
// 		--framework playwright \
// 		--language typescript \
// 		--output integration_create_gamescore_get_recent_objects.spec.ts \
// 		--output-dir /home/runner/work/parse-server-example/parse-server-example/spec \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/parse-server-example/parse-server-example/spec/scenario_create_gamescore_get_recent_objects.json

// Import of required libraries
import { test, expect } from '@playwright/test';
import { SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
let URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:1337");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    let client =  new SkyrampClient();

    // Declaration of variables
    let classes = "GameScore";

    // Request Body
    const classesPostRequestBody = `{
            "playerName": "TestBot Player",
            "score": 9500
        }`
    
    // Execute Request
    let classesPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/parse/classes/{classes}",
        method:"POST",
        body:classesPostRequestBody,
        headers:{"X-Parse-Master-Key": "SKYRAMP_PLACEHOLDER_TOKEN"},
        pathParams:{"classes": classes}
    });

    // Generated Assertions
    expect(classesPostResponse.statusCode, 'status code').toBe(201);

    // Request Body
    const getRecentObjectsPostRequestBody = `{
            "className": "GameScore",
            "limit": 5
        }`
    
    // Execute Request
    let getRecentObjectsPostResponse = await client.sendRequest({
        url:URL_localhost,
        path:"/parse/functions/getRecentObjects",
        method:"POST",
        body:getRecentObjectsPostRequestBody,
        headers:{"X-Parse-Master-Key": "SKYRAMP_PLACEHOLDER_TOKEN"}
    });

    // Generated Assertions
    expect(getRecentObjectsPostResponse.statusCode, 'status code').toBe(200);
});

